### ISSUE TITLE
Unable to install prepackaged .deb on (k)Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by hidden-r4d** [Blobfolio/refract#1]
I downloaded the [the latest deb](https://github.com/Blobfolio/refract/releases/download/v0.7.6/refract_0.7.6-1_amd64.deb) and attempted to install via gdebi, however the results are as follows:

```
> gdebi ./refract_0.7.6-1_amd64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libgdk-pixbuf-2.0-0 (>= 2.25.2)
```

**Comment by hidden-r4d** [comment]
Following the manual instructions in the readme yield [these](https://pastebin.com/NsDeJDpr) results.

**Comment by hidden-r4d** [comment]
When extracting the executable from the .deb, it seems to work completely fine.

**Comment by joshstoik1** [comment]
Thanks for reporting, @hidden-r4d!

The `.deb` packages attached to each release are compiled under Debian `Bullseye`, which use newer versions of GTK than Ubuntu `Focal`. It looks like `libgdk-pixbuf-2.0-0` didn't land in Ubuntu until `Hirsute (21.04)`. As you discovered, the binary _might_ work exactly as it should anyway, but package managers won't proceed with the installation.

The build issue is related to https://github.com/alexcrichton/cmake-rs/issues/138. Because it was introduced in a minor release, Cargo is happily pulling down the newer, broken version rather than the one explicitly stated in `jpegxl-sys`'s manifest. On the bright side, it looks like there is already a [pull request](https://github.com/alexcrichton/cmake-rs/pull/139) to address the issue, so hopefully the problem will be short-lived. :wink:

If you really wanted to build Refract from source in the meantime, you could download and extract https://github.com/inflation/jpegxl-sys/archive/refs/tags/v0.6.1.tar.gz into Refract's source root and make the following two changes:

**refract_core/Cargo.toml**
```toml
[dependencies.jpegxl-sys]
version = "0.6.1" # Bump the version.
path = "../jpegxl-sys-0.6.1" # Point this to the folder you extracted, probably named thusly.
```

**jpegxl-sys-0.6.1/Cargo.toml**
```toml
[build-dependencies]
cmake = "=0.1.45" # Add the "=" to the version.
```

I'll leave this ticket open until `cmake-rs` has fixed itself, in case anybody else runs into the same issue.
